server:
  port: 80

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:mysql://localhost:3307/lz_blog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: 'root'
    password: 'Zyh20010605'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    password: Zyh20010605
    port: 6379

mybatis:
  type-aliases-package: com.lan5th.blog.pojo
  mapper-locations: classpath:dao/*.xml
  configuration: #代替配置文件的功能
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
  config: classpath:config/log4j2-prod.xml

